spring.datasource.url=jdbc:postgresql://dpg-d8c12tvavr4c73ecgptg-a.singapore-postgres.render.com/moneymanager_n5b5
spring.datasource.username=moneymanager_n5b5_user
spring.datasource.password=dNM4EmH6Tl3FC4vG0Ey47eBHXj98BdhB
